name: native_updater
description: Flutter package for prompting users to update with a native dialog whether using the app store version or any version at the user's discretion.
publish_to: "none"

version: 0.1.2
homepage: https://github.com/ofload/native_updater

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # url_launcher will help us to trigger app store / play store url from our app.
  url_launcher: ^6.3.2
  # Enables In App Updates on Android using the official Android APIs.
  in_app_update:
    git:
      url: https://github.com/jonasbark/flutter_in_app_update
      ref: master
  # package_info will help us to find current installed version of application.
  package_info_plus: ^8.3.1
  dio: ^5.9.0

flutter:
  assets:
    - packages/native_updater/images/google_play.png
